exclude:
- /iOS/Pods/.*
- /iOS/VSD/Base\.lproj
- /iOS/VSD/CABitOperations\.h
- /iOS/VSD/CADebugMacros\.cpp
- /iOS/VSD/CADebugMacros\.h
- /iOS/VSD/CAMath\.h
- /iOS/VSD/CAStreamBasicDescription\.cpp
- /iOS/VSD/CAStreamBasicDescription\.h
- /iOS/VSD/CAXException\.cpp
- /iOS/VSD/CAXException\.h
- /iOS/VSD/emd\.cpp
- /iOS/VSD/emd\.h
- /iOS/VSD/en\.lproj
- /iOS/VSD/filt\.cpp
- /iOS/VSD/filt\.h
- /iOS/VSD/Images\.xcassets
- /iOS/VSD/processAudio\.cpp
- /iOS/VSD/processAudio_emxutil\.cpp
- /iOS/VSD/processAudio_emxutil\.h
- /iOS/VSD/processAudio\.h
- /iOS/VSD/processAudio_initialize\.cpp
- /iOS/VSD/processAudio_initialize\.h
- /iOS/VSD/processAudio_terminate\.cpp
- /iOS/VSD/processAudio_terminate\.h
- /iOS/VSD/processAudio_types\.h
- /iOS/VSD/pwchcore\.cpp
- /iOS/VSD/pwchcore\.h
- /iOS/VSD/rtwtypes\.h
- /iOS/VSD/spline\.cpp
- /iOS/VSD/spline\.h
- /iOS/VSD/VSD-Info\.plist
- /iOS/VSD/VSD-Prefix\.pch
- .*/Python/emd\.py
- .*/Python/utils\.py
- .*/Python/visualization\.py