osx_image: xcode10.2
language: swift
script:
 - set -o pipefail && xcodebuild -workspace iOS/VSD.xcodeproj/project.xcworkspace -scheme "VSDUITests" -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' test
