osx_image: xcode9.4
language: objective-c
cache: cocoapods
podfile: iOS/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
script:
 - set -o pipefail && xcodebuild test -workspace iOS/VSD.xcworkspace -scheme VSD -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,name=iPhone SE"
