/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VSD_JNI */

#ifndef _Included_VSD_JNI
#define _Included_VSD_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VSD_JNI
 * Method:    processAudio
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_VSD_1JNI_processAudio
  (JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
