/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VSDJNI */

#ifndef _Included_VSDJNI
#define _Included_VSDJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VSDJNI
 * Method:    processAudio
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_VSDJNI_processAudio
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
