# CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    parallelism: 4

    working_directory: ~/project

    steps:
      - checkout
        
      # build C Linux Lib
      - run:
          name: build C Linux lib
          command: |
            cd Generic/C_JAVA/; make all -f Makefile_linux
      # build Java Linux Lib
      - run:
          name: build Java Linux lib
          command: |
            cd Generic/C_JAVA/; make all -f Makefile_java
