# CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    parallelism: 4

    working_directory: ~/project

    steps:
      - checkout
        
      # Build C Linux Lib
      - run:
          name: Build C Linux lib
          command: |
            cd Generic/C_JAVA/; make all -f Makefile_linux
      # Build Java Linux Lib
      - run:
          name: Build Java Linux lib
          command: |
            cd Generic/C_JAVA/; make all -f Makefile_java_linux; cp lib/libVSDJNI.so libVSDJNI.so
      # Build Java Test App
      - run:
          name: Build Java Test App
          command: |
            cd Generic/C_JAVA/; javac VSDJNI.java -h .;
      # Run Java Test App
      - run:
          name: Run Java Test App
          command: |
            cd Generic/C_JAVA/; java -cp . -Djava.library.path=$(pwd) VSDJNI 
            
