# CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    parallelism: 4

    working_directory: ~/project/Generic/C/Linux/

    steps:
      - checkout
        

      # ls!
      - run:
          name: List Dir
          command: |
            ls -lah

      # build!
      - run:
          name: build C Linux lib
          command: |
            cd Generic/C/Linux/; make all