# CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    parallelism: 4

    working_directory: ~/project

    steps:
      - checkout
        
      # Build C Linux Lib
      - run:
          name: Build C Linux lib
          command: |
            cd Generic/C_JAVA/; make all -f Makefile_linux
      # Build JNI Linux Lib
      - run:
          name: Build JNI Linux lib
          command: |
            cd Generic/C_JAVA/; make all -f Makefile_java_linux; cp lib/libVSDJNI.so libVSDJNI.so; cp lib/libVSDJNI.so VSDJNI/src/main/java/com/nfsindustries/libVSDJNI.so;
      # Build Maven
      - run:
          name: Build Maven
          command: |
            cd Generic/C_JAVA/VSDJNI/; mvn clean install surefire-report:report-only -Dskip.unit.tests=false -Djava.library.path=/Users/nfacchin/dev/maxmouse/Stress-Detector/Generic/C_JAVA/lib/;
      # Build Java Test App
      - run:
          name: Build Java Test App
          command: |
            cd Generic/C_JAVA/VSDJNI/src/main/java/com/nfsindustries/; javac VSDJNI.java -h .;
      # Run Java Test App
      - run:
          name: Run Java Test App
          command: |
            cd Generic/C_JAVA/VSDJNI/src/main/java/com/nfsindustries/; java -cp . -Djava.library.path=$(pwd) VSDJNI
            
