# CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ubuntu:16.04
    parallelism: 4

    working_directory: ~/repo/

    steps:
      - checkout
        
      # build!
      - run:
          name: build C Linux lib
          command: |
            make -f Generic/C/Linux/Makefile