source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'VSD' do
  
    target 'VSDTests' do
      pod 'KIF', '~> 3.5.2’, :configurations => ['Debug']
    end
end
