/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VSD */

#ifndef _Included_VSD
#define _Included_VSD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VSD
 * Method:    vsd
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_VSD_vsd
  (JNIEnv *, jclass, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
